### ISSUE TITLE
ada BUG~~~

### ISSUE THREAD

**Issue by ICol3** [MariefW/AIM#2]
itu disana
![langkah1](https://user-images.githubusercontent.com/28957124/46647510-eb811780-cbc2-11e8-8f07-365300955ddd.png)
![langkah3](https://user-images.githubusercontent.com/28957124/46647511-ec19ae00-cbc2-11e8-91ac-07adc50ab109.png)
![t-shirt](https://user-images.githubusercontent.com/28957124/46647513-ec19ae00-cbc2-11e8-9736-79ed9ac85b8c.png)

**Comment by MariefW** [comment]
issue sepeerti ap?
